import React, { useState } from "react";

/**
 * Basic board form for creating a post.
 * Data model:
 * - id: Long (generated by backend)
 * - title: String
 * - contents: String
 * - registerId: Long
 * - hitCount: int
 *
 * Usage: place <BoardForm /> in a page. Adjust POST URL to match your backend.
 */

export default function BoardForm() {
    const [title, setTitle] = useState("");
    const [contents, setContents] = useState("");
    const [registerId, setRegisterId] = useState("");
    const [hitCount, setHitCount] = useState(0);
    const [loading, setLoading] = useState(false);
    const [message, setMessage] = useState(null);
    const [error, setError] = useState(null);

    const validate = () => {
        if (!title.trim()) return "제목을 입력하세요.";
        if (!contents.trim()) return "내용을 입력하세요.";
        if (!registerId.toString().trim() || Number.isNaN(Number(registerId)))
            return "등록자 ID는 숫자여야 합니다.";
        return null;
    };

    const handleSubmit = async (e) => {
        e.preventDefault();
        setError(null);
        setMessage(null);

        const v = validate();
        if (v) {
            setError(v);
            return;
        }

        const payload = {
            // id is usually generated by backend
            title: title.trim(),
            contents: contents.trim(),
            registerId: Number(registerId),
            hitCount: Number(hitCount) || 0,
        };

        try {
            setLoading(true);
            // Adjust endpoint as needed
            const res = await fetch("/api/boards", {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify(payload),
            });

            if (!res.ok) {
                const text = await res.text();
                throw new Error(text || `서버 오류: ${res.status}`);
            }

            const data = await res.json();
            setMessage("게시물이 등록되었습니다.");
            // reset form (optionally keep registerId)
            setTitle("");
            setContents("");
            setHitCount(0);
            // If backend returns created id you can use data.id
            console.log("created:", data);
        } catch (err) {
            setError(err.message || "등록 중 오류가 발생했습니다.");
        } finally {
            setLoading(false);
        }
    };

    const handleReset = () => {
        setTitle("");
        setContents("");
        setRegisterId("");
        setHitCount(0);
        setError(null);
        setMessage(null);
    };

    return (
        <div style={styles.container}>
            <h2 style={styles.heading}>게시판 글쓰기</h2>

            <form onSubmit={handleSubmit} style={styles.form}>
                <label style={styles.label}>
                    제목
                    <input
                        type="text"
                        value={title}
                        onChange={(e) => setTitle(e.target.value)}
                        style={styles.input}
                        placeholder="제목을 입력하세요"
                    />
                </label>

                <label style={styles.label}>
                    내용
                    <textarea
                        value={contents}
                        onChange={(e) => setContents(e.target.value)}
                        style={styles.textarea}
                        placeholder="내용을 입력하세요"
                        rows={8}
                    />
                </label>

                <label style={styles.label}>
                    등록자 ID
                    <input
                        type="number"
                        value={registerId}
                        onChange={(e) => setRegisterId(e.target.value)}
                        style={styles.input}
                        placeholder="등록자 ID (숫자)"
                    />
                </label>

                <label style={styles.label}>
                    조회수
                    <input
                        type="number"
                        value={hitCount}
                        onChange={(e) => setHitCount(e.target.value)}
                        style={styles.input}
                        min={0}
                    />
                </label>

                {error && <div style={styles.error}>{error}</div>}
                {message && <div style={styles.success}>{message}</div>}

                <div style={styles.actions}>
                    <button type="submit" disabled={loading} style={styles.buttonPrimary}>
                        {loading ? "전송중..." : "등록"}
                    </button>
                    <button
                        type="button"
                        onClick={handleReset}
                        disabled={loading}
                        style={styles.button}
                    >
                        초기화
                    </button>
                </div>
            </form>
        </div>
    );
}

const styles = {
    container: {
        maxWidth: 800,
        margin: "24px auto",
        padding: 16,
        border: "1px solid #e0e0e0",
        borderRadius: 8,
        fontFamily: "Arial, sans-serif",
    },
    heading: { margin: "0 0 12px 0" },
    form: { display: "flex", flexDirection: "column", gap: 12 },
    label: { display: "flex", flexDirection: "column", fontSize: 14 },
    input: {
        padding: 8,
        fontSize: 14,
        borderRadius: 4,
        border: "1px solid #ccc",
        marginTop: 6,
    },
    textarea: {
        padding: 8,
        fontSize: 14,
        borderRadius: 4,
        border: "1px solid #ccc",
        marginTop: 6,
        resize: "vertical",
    },
    actions: { display: "flex", gap: 8, marginTop: 8 },
    buttonPrimary: {
        padding: "8px 12px",
        background: "#0078d4",
        color: "#fff",
        border: "none",
        borderRadius: 4,
        cursor: "pointer",
    },
    button: {
        padding: "8px 12px",
        background: "#f3f3f3",
        border: "1px solid #ccc",
        borderRadius: 4,
        cursor: "pointer",
    },
    error: { color: "#a80000", marginTop: 6 },
    success: { color: "#007700", marginTop: 6 },
};